# Generated by Django 4.2.7 on 2023-12-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tournament', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('countOfPlayers', models.IntegerField()),
                ('coach', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pnumber', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tournaments',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='SquadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.team')),
            ],
            options={
                'verbose_name': 'SquadList',
                'verbose_name_plural': 'SquadList',
            },
        ),
    ]
