# Generated by Django 4.2.7 on 2023-12-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('mini_player_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camp_photos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tournaments',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('training_name', models.CharField(max_length=255)),
                ('training_description', models.TextField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='content.footballcamp')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='footballcamp',
            name='photo_gallery',
            field=models.ManyToManyField(blank=True, related_name='camps', to='content.photo'),
        ),
    ]
