# Generated by Django 4.2.7 on 2023-12-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tournaments'),
        ),
    ]
