# Generated by Django 4.2.7 on 2023-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_team_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pnumber',
            field=models.CharField(max_length=12),
        ),
    ]
