# Generated by Django 4.2.7 on 2023-12-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_team_pnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='footballcamp',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='footballcamp',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='content/static/content/images/logo'),
        ),
    ]
