# Generated by Django 4.2.7 on 2023-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_contact_phone_number_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFootball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='footballcamp',
            name='logo',
            field=models.ImageField(null=True, upload_to='content/static/content/images/camps'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='content/static/content/images/teams'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='logo',
            field=models.ImageField(null=True, upload_to='content/static/content/images/tournaments'),
        ),
    ]
