# Generated by Django 4.2.7 on 2023-12-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_newsfootball_alter_footballcamp_logo_alter_team_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfootball',
            name='photo',
            field=models.ImageField(upload_to='content/static/content/images/news'),
        ),
    ]
