# Generated by Django 4.2.7 on 2023-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_newsfootball_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfootball',
            name='time_of_publication',
            field=models.DateTimeField(null=True),
        ),
    ]
