# Generated by Django 4.2.7 on 2023-12-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_newsfootball_time_of_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='pcoach',
            field=models.ImageField(null=True, upload_to='content/static/content/images/coaches'),
        ),
        migrations.AddField(
            model_name='training',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_photos', to='content.trainer'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_trainings', to='content.trainer'),
        ),
    ]
